spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ORDER-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/orders/**
        - id: PRODUCT-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**
        - id: INVENTORY-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/inventory/**
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9099/eureka

springdoc:
  api-docs:
   enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs/products
        name: Product Service
      - url: /v3/api-docs/orders
        name: Order Service
      - url: /v3/api-docs/inventory
        name: Inventory Service